#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

REMOVE="rm -rf ./packages/client/public/sw.js public/sw.js.map ./packages/client/public/workbox-*.js ./packages/client/public/workbox-*.js.map ./packages/client/.next"
# remove files from previous builds
eval $REMOVE

# lint and build
yarn run lint

# format code
yarn run format

# run build and test for truthy
cd ./packages/client && yarn run build
# test for last command executed
if [ $? -eq 0 ]; then
    # remove build files
    eval $REMOVE
    echo -n "Build Successful 😆!
  Enter the file for the input to be staged for commit.
  Separate multiple files with a space.
  For example: ./husky.sh stage app.ts src/index.tsx or . # to stage all files.
    Files to commit : "
    # read files
    eval "git add ."
    exit 0
    
else
    echo "Oops! Build failed 😢."
    exit 130
fi
